---
title: "p8105_hw5_jh4617"
author: "Junjie Hu"
date: "2023-11-11"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r echo = FALSE}
library(tidyverse)
library(purrr)
library(rvest)
```

# Problem 1

## Imported data, created `city_state` variable
```{r}
homicide_df =
  read.csv("homicide-data.csv")|>
  janitor::clean_names() |>
  mutate(city_state = paste(city, state, sep = ","))
```

The raw data obtains `r nrow(homicide_df)` observations and `r ncol(homicide_df)` variables, including `r names(homicide_df)`.

## Summarized with cities
```{r}
homicide_df |>
  group_by(city) |>
  summarize(n = n()) |>
  knitr::kable()

homicide_df |>
  filter(disposition %in% c ("Closed without arrest", "Open/No arrest")) |>
  group_by(city) |>
  summarize(n = n()) |>
  knitr::kable()
```

## Estimated the proportion of homicide that are unsolved
```{r}

homicide_df |>
  filter(city_state == "Baltimore,MD") |>
  summarize(unsolved = sum(disposition %in% c("Closed without arrest", "Open/No arrest")),
            total = n()) %>%
  {prop.test(.$unsolved, .$total)} |>
  broom::tidy()

```

## Proportion for each cities
```{r}
homicide_df |>
  group_by(city) |>
  summarize(unsolved = sum(disposition %in% c("Closed without arrest", "Open/No arrest")),
            total = n()) %>%
  {prop.test(.$unsolved, .$total)} |>
  broom::tidy()
```


# Problem 2
```{r}

file_list = 
  list.files(path = "data", full.names = TRUE) 

load_files = function(x){
  
  arm =
    if_else(str_detect(x, "^con"), "control", "experimental")
  
  id = 
    str_extract(x, "\\d{2}")
  
data = 
    read.csv(x) |>
    janitor::clean_names()|>
    mutate(arm = arm, id = id)
    
}

output = 
  map(file_list, load_files) 

combined_df = 
  bind_rows(output)
```


